apiVersion: batch/v1
kind: CronJob
metadata:
  name: birthbot-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      suspend: false
      template:
        spec:
          containers:
            - name: birthbot-cron
              image: ghcr.io/ziwooda/gitops-study:sha-f044b44
              imagePullPolicy: IfNotPresent
              env:
                - name: SLACK_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: slack-token
                      key: token
                      optional: false
          imagePullSecrets:
            - name: birth-github
          tolerations:
            - key: "node.kubernetes.io/not-ready"
              operator: "Exists"
              effect: "NoExecute"
              tolerationSeconds: 6000
            - key: "node.kubernetes.io/unreachable"
              operator: "Exists"
              effect: "NoExecute"
              tolerationSeconds: 6000
          restartPolicy: OnFailure
