apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2doY3IuaW8iOnsidXNlcm5hbWUiOiJjbG91ZC1jbHViIiwicGFzc3dvcmQiOiJnaHBfYUZ4c2s3Q3A3VW50TTk3bGVhdU1OTHU0VlNkb1JOM3NtU1R4IiwiYXV0aCI6IlkyeHZkV1F0WTJ4MVlqcG5hSEJmWVVaNGMyczNRM0EzVlc1MFRUazNiR1ZoZFUxT1RIVTBWbE5rYjFKT00zTnRVMVI0In19fQ==
kind: Secret
metadata:
  creationTimestamp: "2023-01-02T07:57:53Z"
  name: birth-github
  namespace: birthbot
  resourceVersion: "1633342"
  uid: 69de4065-fb7b-4680-a5c6-2fda007c9cc6
type: kubernetes.io/dockerconfigjson
